services:
  mongodb:
    image: mongo:7.0
    container_name: rescue3d-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: rescue3d

volumes:
  mongo-data:
